### ISSUE TITLE
问卷填写

### ISSUE THREAD

**Issue by usas-xiaocai** [tencent-ailab/hok_env#1]
你好，我提交了问卷，但是没有收到回应，是需要其他的资料吗

**Comment by hongyangqin** [comment]
第一批的申请的用户, 我们已于8月时通过邮件回复协议签署方式

对于已完成协议签署的用户, 我们预计下周通过邮件发送gamecore下载链接以及访问证书
第二批申请的用户, 也预计是下周统一回复协议签署方式

---

该方式为临时申请方式, 后续会在官网开放申请入口, 届时用户可在官网完成所有操作
