### ISSUE TITLE
ABSTool

### ISSUE THREAD

**Issue by Shuilin123** [tencent-ailab/hok_env#10]
Where can I get the replay tool ABSTool.exe?

**Comment by hongyangqin** [comment]
https://aiarena.tencent.com/aiarena/en/open-gamecore

![image](https://user-images.githubusercontent.com/17291060/205415878-5f6465f9-dbf3-48ad-a338-24cc1c2baf9a.png)

![image](https://user-images.githubusercontent.com/17291060/205415837-6c89f338-5dc7-44d5-b90d-b8f8bb6be101.png)

**Comment by Shuilin123** [comment]
thank you for the response
