### ISSUE TITLE
python test_env.py [Warning] Check game status error, stop it directly. HTTPConnectionPool(host='172.29.241.1', port=23432): Max retries exceeded with url: /v2/stopGame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fddd0e6add8>: Failed to establish a new connection: [Errno 110] Connection timed out',))

### ISSUE THREAD

**Issue by Logan-lxw** [tencent-ailab/hok_env#14]
I am really thankful for your reply.And I solved some problems with your help.But unfortunately，I meet some new problems now.
First,I got the nameserver and connect it with my command telnet.

![image](https://user-images.githubusercontent.com/70302771/209087950-ae1e7501-5e48-4251-b33f-5a663c4ea9c9.png)

Then I delete the inbound rule as what you tell me to do.But when I start python test_env.py ,there is still some fault there.
![image](https://user-images.githubusercontent.com/70302771/209087870-2e1db252-09c5-42d4-adca-26296d91b852.png)

I am looking forward to your reply.Thank you! @@hongyangqin @Caiderkoujiao @tencent-ailab @HIT-jixiyang

_Originally posted by @Logan-lxw in https://github.com/tencent-ailab/hok_env/issues/11#issuecomment-1362536285_

**Comment by hongyangqin** [comment]
If you can telnet to the target server successfully, no need to reset the inbound rule of firewall again.
So retry to telnet the server to check if the network is accesable.

**Comment by Logan-lxw** [comment]
Thanks for your reply again! Now I solved the problem.
