### ISSUE TITLE
The program is stuck at "parse_state, sgame_id = self.lib_proccessor.RecvAIFrameState(self.game_launcher.addrs[id])"

### ISSUE THREAD

**Issue by peterwu4084** [tencent-ailab/hok_env#15]
![屏幕截图 2023-01-02 154815](https://user-images.githubusercontent.com/38035170/210205049-5354119e-9918-417d-967f-d1bbe00d717f.png)
I tested the gamecore with the demo script in WSL but it seemed the program stucked at this position.
I am looking for help.Thank you!

**Comment by sxzhuang** [comment]
I also met the similar problem but the error reported were different from @peterwu4084 . I succeed to start gamecore in windows, but when I tried the domo script in wsl2, ran python test_env.py, I met the following problem.
```
127.0.0.1:23432 127.0.0.1
load config.dat:  /home/love7/workspace/hok_env-master/hok_env/hok/env1v1.py
load config...
146[skill=80121]        127.0.0.1       35300   1000
 [('146', '80121'), '127.0.0.1', '35300', '1000'] ./hok/sgame_simulator.conf
146[skill=80121]        127.0.0.1       35301   1000
 [('146', '80121'), '127.0.0.1', '35301', '1000'] ./hok/sgame_simulator.conf
======= test_send_action
try to get first state... [False, False]
Pb2Struct::InitChangeType usedefault=offline
Pb2Struct::InitChangeType change_type=offline
Pb2Struct::InitMainHeroType, no main_hero_type, use default mvp
Traceback (most recent call last):
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f27df500650>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=23432): Max retries exceeded with url: /v2/stopGame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f27df500650>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_env.py", line 124, in <module>
    config_dicts=[{"hero": "diaochan", "skill": "frenzy"} for _ in range(2)],
  File "test_env.py", line 48, in test_send_action
    use_common_ai=common_ai, eval=eval, config_dicts=config_dicts, render=None
  File "/home/love7/workspace/hok_env-master/hok_env/hok/env1v1.py", line 716, in reset
    self.game_launcher.start(config_dicts, common_config)
  File "/home/love7/workspace/hok_env-master/hok_env/hok/gamecore_utils.py", line 438, in start
    self.remote_gc_proc.remote_stop()
  File "/home/love7/workspace/hok_env-master/hok_env/hok/gamecore_utils.py", line 301, in remote_stop
    self.launch_server, "stopGame", self.user_token, data, ignore_resp=True
  File "/home/love7/workspace/hok_env-master/hok_env/hok/gamecore_utils.py", line 272, in send_http_request
    resp = requests.post(url=url, json=data, headers=headers, verify=False)
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=23432): Max retries exceeded with url: /v2/stopGame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f27df500650>: Failed to establish a new connection: [Errno 111] Connection refused'))
check game stopped.
[Warning] Check game status error, stop it directly. HTTPConnectionPool(host='127.0.0.1', port=23432): Max retries exceeded with url: /v2/stopGame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f27e2e77c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
```
I am looking for help! Thanks a lot!

**Comment by peterwu4084** [comment]
> I also met the similar problem but the error reported were different from @peterwu4084 . I succeed to start gamecore in windows, but when I tried the domo script in wsl2, ran python test_env.py, I met the following problem.
> 
> ```
> 127.0.0.1:23432 127.0.0.1
> load config.dat:  /home/love7/workspace/hok_env-master/hok_env/hok/env1v1.py
> load config...
> 146[skill=80121]        127.0.0.1       35300   1000
>  [('146', '80121'), '127.0.0.1', '35300', '1000'] ./hok/sgame_simulator.conf
> 146[skill=80121]        127.0.0.1       35301   1000
>  [('146', '80121'), '127.0.0.1', '35301', '1000'] ./hok/sgame_simulator.conf
> ======= test_send_action
> try to get first state... [False, False]
> Pb2Struct::InitChangeType usedefault=offline
> Pb2Struct::InitChangeType change_type=offline
> Pb2Struct::InitMainHeroType, no main_hero_type, use default mvp
> Traceback (most recent call last):
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connection.py", line 175, in _new_conn
>     (self._dns_host, self.port), self.timeout, **extra_kw
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/util/connection.py", line 95, in create_connection
>     raise err
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/util/connection.py", line 85, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
>     chunked=chunked,
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connectionpool.py", line 398, in _make_request
>     conn.request(method, url, **httplib_request_kw)
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connection.py", line 239, in request
>     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/http/client.py", line 1281, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/http/client.py", line 1327, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/http/client.py", line 1276, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/http/client.py", line 1036, in _send_output
>     self.send(msg)
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/http/client.py", line 976, in send
>     self.connect()
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connection.py", line 205, in connect
>     conn = self._new_conn()
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connection.py", line 187, in _new_conn
>     self, "Failed to establish a new connection: %s" % e
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f27df500650>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
>     timeout=timeout,
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
>     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=23432): Max retries exceeded with url: /v2/stopGame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f27df500650>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test_env.py", line 124, in <module>
>     config_dicts=[{"hero": "diaochan", "skill": "frenzy"} for _ in range(2)],
>   File "test_env.py", line 48, in test_send_action
>     use_common_ai=common_ai, eval=eval, config_dicts=config_dicts, render=None
>   File "/home/love7/workspace/hok_env-master/hok_env/hok/env1v1.py", line 716, in reset
>     self.game_launcher.start(config_dicts, common_config)
>   File "/home/love7/workspace/hok_env-master/hok_env/hok/gamecore_utils.py", line 438, in start
>     self.remote_gc_proc.remote_stop()
>   File "/home/love7/workspace/hok_env-master/hok_env/hok/gamecore_utils.py", line 301, in remote_stop
>     self.launch_server, "stopGame", self.user_token, data, ignore_resp=True
>   File "/home/love7/workspace/hok_env-master/hok_env/hok/gamecore_utils.py", line 272, in send_http_request
>     resp = requests.post(url=url, json=data, headers=headers, verify=False)
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/api.py", line 115, in post
>     return request("post", url, data=data, json=json, **kwargs)
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/api.py", line 59, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/love7/anaconda3/envs/hok/lib/python3.7/site-packages/requests/adapters.py", line 565, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=23432): Max retries exceeded with url: /v2/stopGame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f27df500650>: Failed to establish a new connection: [Errno 111] Connection refused'))
> check game stopped.
> [Warning] Check game status error, stop it directly. HTTPConnectionPool(host='127.0.0.1', port=23432): Max retries exceeded with url: /v2/stopGame (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f27e2e77c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
> ```
> 
> I am looking for help! Thanks a lot!

You need to change the SERVER_ADDR in test_env.py. See details in https://github.com/tencent-ailab/hok_env/issues/11

**Comment by hongyangqin** [comment]
@peterwu4084 Can you run the gamecore (common ai only) manually on the windows side?

Run with`cmd.exe`
```
 cd gamecore\bin
 set PATH=%PATH%;..\lib\
 .\sgame_simulator_remote_zmq.exe .\sgame_simulator.common.conf
```
where `sgame_simulator.common.conf` is 
```
{
    "abs_file": "../scene/1V1.abs",
    "core_assets": "../core_assets",
    "game_id": "kaiwu-base-35401-35400-6842-1669963820108111766-217",
    "hero_conf": [
        {
            "hero_id": 199
        },
        {
            "hero_id": 199
        }
    ]
}
```

**Comment by peterwu4084** [comment]
> @peterwu4084 Can you run the gamecore (common ai only) manually on the windows side?
> 
> Run with`cmd.exe`
> 
> ```
>  cd gamecore\bin
>  set PATH=%PATH%;..\lib\
>  .\sgame_simulator_remote_zmq.exe .\sgame_simulator.common.conf
> ```
> 
> where `sgame_simulator.common.conf` is
> 
> ```
> {
>     "abs_file": "../scene/1V1.abs",
>     "core_assets": "../core_assets",
>     "game_id": "kaiwu-base-35401-35400-6842-1669963820108111766-217",
>     "hero_conf": [
>         {
>             "hero_id": 199
>         },
>         {
>             "hero_id": 199
>         }
>     ]
> }
> ```

It's ok.
![屏幕截图_20230112_210602](https://user-images.githubusercontent.com/38035170/212074326-6cebf122-c455-4436-af3e-f4b1de743524.png)

**Comment by hongyangqin** [comment]
@peterwu4084 I can not reproduce the problem on my windows.Please provide more detail about how you run the test.

**Comment by peterwu4084** [comment]
> 

1. I ran ` .\gamecore-server.exe server` on the windows side and the following infomation was printed.
![屏幕截图_20230119_202609](https://user-images.githubusercontent.com/38035170/213442858-cd5fd5b0-cec5-4f36-9cb6-32dfbf27fea7.png)
2. `cat /etc/resolve.conf` printed `nameserver 172.20.96.1`. So I changed the code in `test_env.py` as following. 
![屏幕截图_20230119_203432](https://user-images.githubusercontent.com/38035170/213444395-bdcaf290-d8a0-4516-bd70-83e4fc0144ff.png)
3. Then I ran `python test_env.py` and the program got stucked. But the gameserver printed some new message as following.
![屏幕截图_20230119_204027](https://user-images.githubusercontent.com/38035170/213445347-a3ffcb9f-7751-4ae1-a7cb-9d4caaf11752.png)
4. I run `netstat -nlp` and got this message.
![屏幕截图_20230119_204138](https://user-images.githubusercontent.com/38035170/213445593-d55a23a5-7288-4ff8-8c46-e4a1bbf01762.png)
5. Ran` telnet 127.0.0.1 23333` and got this message.
![image](https://user-images.githubusercontent.com/38035170/213445856-0a7586f7-b906-4e8d-9172-df2939a60640.png)

**Comment by Song-Weifeng** [comment]
> ![屏幕截图 2023-01-02 154815](https://user-images.githubusercontent.com/38035170/210205049-5354119e-9918-417d-967f-d1bbe00d717f.png) I tested the gamecore with the demo script in WSL but it seemed the program stucked at this position. I am looking for help.Thank you!

do you sovle it ? I meet this problem today.

**Comment by hongyangqin** [comment]
> cat /etc/resolve.conf printed nameserver 172.20.96.1. So I changed the code in test_env.py as following.@peterwu4084

**Comment by Song-Weifeng** [comment]
> The problem has been solved, thank you！

**Comment by peterwu4084** [comment]
> > cat /etc/resolve.conf printed nameserver 172.20.96.1. So I changed the code in test_env.py as following.
> 
> Set `AI_SERVER_ADDR` to `127.0.0.1` if you run the hok_env on the wsl and gamecore on the same windows.
> 
> @peterwu4084 @Song-Weifeng
> 
> > Ran telnet 127.0.0.1 23333 and got this message.
> 
> Not telnet to the gamecore server, please telnet to the `127.0.0.1 35300` when `test_env.py` is running. @peterwu4084


Thank you very much. It works now.
