### ISSUE TITLE
can't find 'ai_simulator_remote' folder

### ISSUE THREAD

**Issue by zszzlmt** [tencent-ailab/hok_env#17]
In Readme.md: 
'Please put the license.dat under the folder:hok_env_gamecore/gamecore/core_assets and add the path of the folder ai_simulator_remote to the system environment variables.'
but I can't find ai_simulator_remote folder either in gamecore or hok_env, what did I missed?
Thanks!

**Comment by hongyangqin** [comment]
`ai_simulator_remote ` has been removed.
