### ISSUE TITLE
can't find 'setup.py'

### ISSUE THREAD

**Issue by zszzlmt** [tencent-ailab/hok_env#18]
In Readme.md:
Install hok_env in python
`# after git clone this repo `
`cd hok_env/hok_env`
`pip install -e .`

but I can't find 'setup.py' to run the last cmd, actually I can't find any 'setup.py' file in this repo except under rl_framework folder. What did I missed?
Thanks!

**Comment by zszzlmt** [comment]
finally, I found a way...
if you are using python3.6, 'pip install -e .' would tell you:
`ERROR: Project file:///mnt/e/hok/hok_env/hok_env has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.`
and you need:

`touch setup.cfg
pip install -e .
rm setup.cfg`

**Comment by hongyangqin** [comment]
Got it, it will be fixed soon.

**Comment by Pika-Lee** [comment]
> finally, I found a way... if you are using python3.6, 'pip install -e .' would tell you: `ERROR: Project file:///mnt/e/hok/hok_env/hok_env has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.` and you need: `touch setup.cfg` `pip install -e .` `rm setup.cfg`

I tried your solution, but it seemed to install nothing but empty packages. Here's the log:

```
xinli@XinLi:~/hok_env/hok_env/hok_env$ touch setup.cfg
xinli@XinLi:~/hok_env/hok_env/hok_env$ sudo pip install -e .
Obtaining file:///home/xinli/hok_env/hok_env/hok_env
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Installing collected packages: UNKNOWN
  Attempting uninstall: UNKNOWN
    Found existing installation: UNKNOWN 0.0.0
    Uninstalling UNKNOWN-0.0.0:
      Successfully uninstalled UNKNOWN-0.0.0
  Running setup.py develop for UNKNOWN
Successfully installed UNKNOWN-0.0.0
```

Does someone know how to fix it? Thanks.

**Comment by hongyangqin** [comment]
fix
