### ISSUE TITLE
Send resp failed: AIFrameStateReturnCode.GET_RESP_FAILED

### ISSUE THREAD

**Issue by wanc97** [tencent-ailab/hok_env#21]
Thanks for open-sourcing this environment. When I execute reset() on this environment, the error in the picture will randomly appear. It may be at the beginning of the program; it may be after running for a day or two; it may be in wsl; it may be in the container. Hope to get an answer, thank you!
![image](https://user-images.githubusercontent.com/70571199/213342119-174321a9-dadf-437e-9585-6395b6cf158b.png)

**Comment by hongyangqin** [comment]
The `interface` is only support one instance, please make sure there is only one actor(one game) for each process.

**Comment by wanc97** [comment]
> instance

Thank you for your reply. I only open one environment (actor) in each process, and different processes are distinguished by runtime id. This problem tends to appear after running for a while.

**Comment by hongyangqin** [comment]
> env1v1.py:512
> self._send(smsg, id)

Please add some logs to show the `smsg` and the `id` when the problem reproduced
