### ISSUE TITLE
cpu docker image with gpu script?

### ISSUE THREAD

**Issue by zszzlmt** [tencent-ailab/hok_env#22]
In the md file below, we are using a cpu docker image with a gpu script, why is this? Thanks！
https://github.com/tencent-ailab/hok_env/blob/master/docs/run_with_prebuilt_image.md

**Comment by zszzlmt** [comment]
besides, according to the md file, there is no /code/code/cpu_code/script/actor_monitor.sh file in this image tencentailab/hok_env:baseline_1v1_cpu_v1.1.0.
`[root@ac04cc09a7c1 /code/code/gpu_code/script]# cd /code/code/cpu_code/script/
[root@ac04cc09a7c1 /code/code/cpu_code/script]# sh start_cpu.sh
learner ip: 127.0.0.1
learner is ok
start setup param
127.0.0.1
['127.0.0.1 root 36000 1']
rm: cannot remove 'send.log': No such file or directory
usage /code/code/cpu_code/script/setup_param.sh gpu_iplist cpu_iplist mem_pool_num task_id task_uuid
start model_pool
start actor
localhost:35200
bash: /code/code/cpu_code/script/actor_monitor.sh: No such file or directory`

**Comment by hongyangqin** [comment]
The code of learner works on both cpu and gpu image.
