### ISSUE TITLE
Max retries erceeded with url

### ISSUE THREAD

**Issue by FENGXIANGZZ** [tencent-ailab/hok_env#24]
I had successfully started the gamcore, however, when I tried to run the test_env.py on wsl2, it failed and reminded me that connectionerror. 

![d3b81de93f38e745dbacf48d2bee148](https://user-images.githubusercontent.com/101922759/216271791-9b63079e-c7e1-48b3-b8ec-18b77475f452.png)

**Comment by FENGXIANGZZ** [comment]
I change the nameserver but there is a new problem. The program stuck in somewhere.
![be29b1756f2f5635b394e0e025e2447](https://user-images.githubusercontent.com/101922759/216556160-9a300428-1831-4658-bd18-13493d88c2ed.png)

**Comment by peterwu4084** [comment]
> It seems that I meet the similiar problem with you @hongyangqin @Logan-lxw @peterwu4084, may you tell me how to solve me? Thank you very much!

I have not solved it.

**Comment by FENGXIANGZZ** [comment]
thank you very much and I finally solve it!
