### ISSUE TITLE
How to run_windows_gamecore_on_linux?

### ISSUE THREAD

**Issue by BITminicc** [tencent-ailab/hok_env#28]
您好由于代码需要运行在linux，我遵照教程[hok_env](https://github.com/tencent-ailab/hok_env)/[docs](https://github.com/tencent-ailab/hok_env/tree/master/docs)/run_windows_gamecore_on_linux.md中的指导申请了license并配置了gamecore。但是有如下问题：
1、输出与示例第二步不同，显示的的是您地址而不是serve. POST   /v1/newGame               --> git.woa.com/hongyangqin/kaiwu-remote-cmd/pkg/server.handler.func1 (4 handlers)
2、可能是由于上一步的不同，使用第三步的python3 /rl_framework/remote-gc-server/test_client.py测试时，返回值400.
3、利用python3 ./test_env.py测试环境时，有如下输出：
load config.dat:  /hok_env/hok/env1v1.py
load config...
146[skill=80121]        127.0.0.1       37300   1000
 [('146', '80121'), '127.0.0.1', '37300', '1000'] ./hok/sgame_simulator.conf
146[skill=80121]        127.0.0.1       37301   1000
 [('146', '80121'), '127.0.0.1', '37301', '1000'] ./hok/sgame_simulator.conf
======= test_send_action
try to get first state... [False, False]
Pb2Struct::InitChangeType usedefault=offline
Pb2Struct::InitChangeType change_type=offline
Pb2Struct::InitMainHeroType, no main_hero_type, use default mvp
但是却停止在此，经过排查是环境reset没有成功，部分log如下：

time="2023-03-07T19:53:02+08:00" level=error msg="Handle Error" X-Request-ID=c40c6986-8264-4ef2-8b9c-de2a87274421 error="fork/exec /rl_framework/remote-gc-server/sgame_simulator_remote_zmq: permission denied"
time="2023-03-07T19:53:02+08:00" level=error msg="Error #01: fork/exec /rl_framework/remote-gc-server/sgame_simulator_remote_zmq: permission denied\n" ClientIP=127.0.0.1 Latency=1248 Method=POST Params="{\"simulator_type\": \"remote_repeat\", \"runtime_id\": \"actor-1v1-0\", \"simulator_config\": {\"hero_conf\": [{\"hero_id\": 141, \"request_info\": {\"ip\": \"127.0.0.1\", \"port\": 37300, \"timeout\": 300000}, \"skill_id\": 80110, \"symbol\": [1514, 1514, 1514, 1514, 1514, 1514, 1514, 1514, 1514, 1514, 3516, 3516, 3516, 3516, 3516, 3516, 3516, 3516, 3516, 3516, 2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520]}, {\"hero_id\": 141, \"request_info\": {\"ip\": \"127.0.0.1\", \"port\": 37301, \"timeout\": 300000}, \"skill_id\": 80110, \"symbol\": [1514, 1514, 1514, 1514, 1514, 1514, 1514, 1514, 1514, 1514, 3516, 3516, 3516, 3516, 3516, 3516, 3516, 3516, 3516, 3516, 2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520, 2520]}]}}" Path=/v2/newGame StatusCode=400
time="2023-03-07T19:53:25+08:00" level=info msg="handle req" ClientIP=127.0.0.1 Latency=46 Method=POST Params="{\"runtime_id\": \"actor-1v1-0\"}" Path=/v2/stopGame StatusCode=200

请问是否是gamecore在linux上没有被正确安装，应该如何使用，还请您详细解答，谢谢。

**Comment by hongyangqin** [comment]
>
>```
> /rl_framework/remote-gc-server/sgame_simulator_remote_zmq: permission denied
>```
文件没有执行权限, 执行以下命令之后再试下:
```
chmod a+x  /rl_framework/remote-gc-server/sgame_simulator_remote_zmq
chmod a+x  /rl_framework/remote-gc-server/sgame_simulator_repeat_zmq
```

**Comment by BITminicc** [comment]
谢谢
