### ISSUE TITLE
unable to use the license Suddenly : SSL peer certificate or SSH remote key was not OK 

### ISSUE THREAD

**Issue by P90-RushB** [tencent-ailab/hok_env#29]
The license has not expired yet and suddenly becomes unusable.

.\sgame_simulator_remote_zmq.exe .\sgame_simulator.common.conf
PlayerNum:2
AbsPath:../scene/1V1.abs
PlayerInfo [CampID:0][HeroID:199][Skill:80104][AutoAi:1][AiServer::0:100] [Symbol 0 0 0] [Request:-1]
PlayerInfo [CampID:1][HeroID:199][Skill:80104][AutoAi:1][AiServer::0:100] [Symbol 0 0 0] [Request:-1]
SGame Simulator Begin
Transfer failed, sleep and retry(1): SSL peer certificate or SSH remote key was not OK
Transfer failed, sleep and retry(2): SSL peer certificate or SSH remote key was not OK
Transfer failed, sleep and retry(3): SSL peer certificate or SSH remote key was not OK
Transfer failed, sleep and retry(4): SSL peer certificate or SSH remote key was not OK
Transfer failed, sleep and retry(5): SSL peer certificate or SSH remote key was not OK
Transfer failed: SSL peer certificate or SSH remote key was not OK
kaiwu::KaiwuLicenseSession::InitGame failed
kaiwu::InitGame failed

**Comment by hongyangqin** [comment]
The certificate has expired. Please try to redownload the license file from the website.
