### ISSUE TITLE
Mistake during the installation

### ISSUE THREAD

**Issue by Kim-Q** [tencent-ailab/hok_env#30]
A small mistake was solved during the installation. Here share to the developers and followers.

When I follow these orders:

>   git clone https://github.com/tencent-ailab/hok_env.git
>   cd hok_env/hok_env/
>   pip install -e .

The pip install works wrong and error as follows: 

>   Installing build dependencies ... done
>   Checking if build backend supports build_editable ... done
>   Getting requirements to build editable ... error
>   error: subprocess-exited-with-error

Then modified the line 12: 

> requires-python = ">=3.6<=3.9"

 to 

> requires-python = ">=3.6"

It works.

**Comment by hongyangqin** [comment]
Known issue. It will be fixed in the next version. Thanks.

Try:
```diff
-requires-python = ">=3.6<=3.9"
+requires-python = ">=3.6, <=3.9"
```
