### ISSUE TITLE
No module named 'hok.lib.interface'

### ISSUE THREAD

**Issue by Pika-Lee** [tencent-ailab/hok_env#31]
Hello, I followed the `README.md`, and was stuck at the following command:  `python3 test_env.py`. Here's the log:

```
xinli@XinLi:~/hok_env/hok_env/hok_env/hok/unit_test$ sudo python3 test_env.py
Traceback (most recent call last):
  File "/home/xinli/hok_env/hok_env/hok_env/hok/unit_test/test_env.py", line 5, in <module>
    from hok import HoK1v1
  File "/usr/local/lib/python3.10/dist-packages/hok/__init__.py", line 11, in <module>
    from hok.env1v1 import HoK1v1
  File "/usr/local/lib/python3.10/dist-packages/hok/env1v1.py", line 22, in <module>
    import hok.lib.interface as interface
ModuleNotFoundError: No module named 'hok.lib.interface'
```

It appeared an error message saying that `No module named 'hok.lib.interface'`. I checked the `~\.local\lib\python3.10\site-packages\hok\lib` folder, it existed four files:

```
interface.cpython-36m-x86_64-linux-gnu.so
interface.cpython-37m-x86_64-linux-gnu.so
interface.cpython-38-x86_64-linux-gnu.so
interface.cpython-39-x86_64-linux-gnu.so
```

Does anyone know how to fix this problem? Thanks.

**Comment by Aki9954** [comment]
I also encountered the same problem as you with this command. I searched hok_env-master and hok_env_gamecore but couldn’t find this module. I hope the author can help solve this problem, thank!

**Comment by hongyangqin** [comment]
Python10 is not supported now. Please use try to use python36~python39.

**Comment by 003userye** [comment]
i change to 3.6,but its not work also

**Comment by huahai2022** [comment]
have you fixed it?
