### ISSUE TITLE
ModuleNotFoundError: No module named 'hok.lib.interface'

### ISSUE THREAD

**Issue by TonFard** [tencent-ailab/hok_env#32]
Traceback (most recent call last):
  File "E:\hok_env\hok_env\hok\unit_test\test_env.py", line 5, in <module>
    from hok import HoK1v1
  File "E:\anaconda\envs\wz\lib\site-packages\hok\__init__.py", line 11, in <module>
    from hok.env1v1 import HoK1v1
  File "E:\anaconda\envs\wz\lib\site-packages\hok\env1v1.py", line 22, in <module>
    import hok.lib.interface as interface
ModuleNotFoundError: No module named 'hok.lib.interface'

**Comment by Pika-Lee** [comment]
Are you using Python 3.10? I had the same problem and solved it by reverting back to Python 3.6.

**Comment by TonFard** [comment]
> 

ok. thank you

**Comment by huahai2022** [comment]
I have the same question, have you fixed it?

**Comment by hongyangqin** [comment]
Python 3.6 to Python 3.9 is presently required. Employing the pre-built image is strongly recommended. To obtain installation instructions, examine the Dockerfile, and for guidance on training procedures, consult [cluster.md](https://github.com/tencent-ailab/hok_env/blob/master/docs/cluster.md).
