### ISSUE TITLE
reading the readme.md,but cannot find some files like it said

### ISSUE THREAD

**Issue by linmi1** [tencent-ailab/hok_env#35]
Q1:the readme say:add the path of the folder `ai_simulator_remote` to the system environment variables.
but I cannot find `ai_simulator_remote`  ,
Q2: In `gamecor/bin`,run the sgame_simulator_remote_zmq.exe,get the log:
``
Usage sgame_simulator_remote_zmq json_conf_file
conf.json.example:
{
        "abs_file" : "./1V1.abs", //required
        "core_assets" : "/path/to/core_assets", //required
        "game_id" : "game-id", //required, should not include '_'
        "hero_conf" :
        [
                {
                        "hero_id" : 112, //required
                        "name" : "name", //optional
                        "request_info" :
                        {
                                "ip" : "127.0.0.1", //ignore if request_id exist
                                "port" : 36000,
                                "request_id" : 0,
                                "timeout" : 3000
                        }, // timeout: optional, default 3000
                        "skill_id" : 80104, //optional, default 80104
                        "symbol" :
                        [
                                1519
                        ]
                },
                {
                        "hero_id" : 112, //required
                        "name" : "name", //optional
                        "request_info" :
                        {
                                "ip" : "127.0.0.1", //ignore if request_id exist
                                "port" : 36000,
                                "request_id" : 0,
                                "timeout" : 3000
                        }, // timeout: optional, default 3000
                        "skill_id" : 80104, //optional, default 80104
                        "symbol" :
                        [
                                1519
                        ]
                }
        ],
        "max_frame_num" : 117200, //optional, default value: 117200
        "request_freq" : 1, //optional, default 1
        "start_frame" : 0 //optional, only for simulator_repeat, default value: 0
}
``
Q3:In `\gamecore\bin`,have no such a file named`.\sgame_simulator.common.conf` ,but have a `sgame_simulator_repeated_zmq`

**Comment by hongyangqin** [comment]
> The content of sgame_simulator.common.conf is shown in the readme.md.
> ```
> {
>     "abs_file": "../scene/1V1.abs",
>     "core_assets": "../core_assets",
>     "game_id": "kaiwu-base-35401-35400-6842-1669963820108111766-217",
>     "hero_conf": [
>         {
>             "hero_id": 199
>         },
>         {
>             "hero_id": 199
>         }
>     ]
> }
> ```


See also https://github.com/tencent-ailab/hok_env/issues/26
