### ISSUE TITLE
ai_simulator_remote

### ISSUE THREAD

**Issue by wuzhedfsfs** [tencent-ailab/hok_env#37]
can't find the  folder ai_simulator_remote, so i can't finish the step of "Please put the license.dat under the folder:hok_env_gamecore/gamecore/core_assets and add the path of the folder ai_simulator_remote to the system environment variables."
Does anyone know how to fix this problem? Thanks.

**Comment by hyukhea** [comment]
ai_simulator_remote  has been removed.

https://github.com/tencent-ailab/hok_env/issues/17#issuecomment-1407932876
https://github.com/tencent-ailab/hok_env/issues/26#issuecomment-1438337267
