### ISSUE TITLE
How to train hok3v3?

### ISSUE THREAD

**Issue by hyukhea** [tencent-ailab/hok_env#38]
I run `aiarena/3v3/learner/train.py` in terminal (wsl2).  Then I got stuck in the `get_sample` loop. 
```
[Debug] The sample is less than half the capacity 0 5000
[Debug] The sample is less than half the capacity 0 5000
[Debug] The sample is less than half the capacity 0 5000
[Debug] The sample is less than half the capacity 0 5000
```

I'm looking forward to some tutorials on 3v3 training.

**Comment by hongyangqin** [comment]
Employing the pre-built image is strongly recommended. To obtain installation instructions, examine the Dockerfile, and for guidance on training procedures, consult [cluster.md](https://github.com/tencent-ailab/hok_env/blob/master/docs/cluster.md).
