### ISSUE TITLE
ModuleNotFoundError: No module named 'hok.hok1v1.lib.interface'

### ISSUE THREAD

**Issue by xiyuewu** [tencent-ailab/hok_env#40]
Thanks for your advice, I have solved this problem by completing hok module path  

Un error message showed as 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\downloads\hok_env-master\hok_env-master\hok_env\hok\hok1v1\__init__.py", line 11, in <module>
    from hok.hok1v1.env1v1 import HoK1v1
  File "e:\downloads\hok_env-master\hok_env-master\hok_env\hok\hok1v1\env1v1.py", line 18, in <module>
    import hok.hok1v1.lib.interface as interface
ModuleNotFoundError: No module named 'hok.hok1v1.lib.interface'


It appeared when I tried python3 test_env.py in the directory hok_env\hok\hok1v1\unit_test
my Python version is Python3.7

**Comment by hongyangqin** [comment]
Have you installed the `hok_env` in your Python site-packages? 
Are you able to find `hok_env/hok/hok1v1/lib/interface.cpython-37m-x86_64-linux-gnu.so`?
(Using the pre-built image is strongly recommended)

**Comment by xiyuewu** [comment]
Sure, I have runned pip install -e . successfully, and there  are four .so files in hok_env/hok/hok1v1/lib/, interface.cpython-37m-x86_64-linux-gnu.so exsits
When I try only `import hok ` module in shell , it runs well

**Comment by hongyangqin** [comment]
It seems that you are running the hok_env on windows. WSL2 are required becase of the `interface.so`

**Comment by huahai2022** [comment]
> Sure, I have runned pip install -e . successfully, and there are four .so files in hok_env/hok/hok1v1/lib/, interface.cpython-37m-x86_64-linux-gnu.so exsits When I try only `import hok ` module in shell , it runs well

Can you explain in detail？thanks

**Comment by 1329844541** [comment]
Why close？I have the same problem，and maybe No body care this program，No one explained the details，and may I should giveup this and use Gym

**Comment by Crosery** [comment]
> Why close？I have the same problem，and maybe No body care this program，No one explained the details，and may I should giveup this and use Gym

You can run it inside WSL2; this error occurs when running it on Windows.
