### ISSUE TITLE
Un problem with step "Run with pre-built image"

### ISSUE THREAD

**Issue by xiyuewu** [tencent-ailab/hok_env#41]
When I tried step "Run with pre-built image"  as Link [https://github.com/tencent-ailab/hok_env/blob/master/docs/run_with_prebuilt_image.md](url) showed， 

4. Run the test_env.py
``` 
cd /hok_env/hok/hok1v1/unit_test
python3 test_env.py
``` 
It can connect to gamecore but nothing happened by ai-server
The log is
![o](https://github.com/tencent-ailab/hok_env/assets/16713686/65181dd8-c3ce-4fd7-ac04-4ba48acd811e)

I have tried using my docker container ip but it didn't work
If i need to change the "AI_SERVER_ADDR" ?

**Comment by hongyangqin** [comment]
Do you run the code suing WSL2?
Ensure that you are able to access the server running within WSL2.
Please try to run a test server within WSL2(for example `python3 -m http.server`) and and access it via the browser outside.

See also: 
https://github.com/tencent-ailab/hok_env/issues/11
https://github.com/tencent-ailab/hok_env/issues/15
