### ISSUE TITLE
missing lib declaration of `lib3v3`

### ISSUE THREAD

**Issue by arctan90** [tencent-ailab/hok_env#42]
[lib3v3 reference is missing](https://github.com/tencent-ailab/hok_env/blob/d25322f6cd2655310f95e6afab639921f9a73a1a/aiarena/3v3/actor/server.py#L8C16-L8C16)

I installed `hok` package using `pip3 install .` under `/Users/yuantao/git/github/tencent-ailab/hok_env/hok_env` folder.

No  Python Wrapper  is found in the `hok_env/hok_env/hok/hok3v3/lib` folder
```
> tree ~/tencent-ailab/hok_env/hok_env/hok/hok3v3/lib
.
├── __init__.py
├── lib3v3.cpython-36m-x86_64-linux-gnu.so
├── lib3v3.cpython-37m-x86_64-linux-gnu.so
├── lib3v3.cpython-38-x86_64-linux-gnu.so
├── lib3v3.cpython-39-x86_64-linux-gnu.so
└── libinterface.so

1 directory, 6 files
```
Because I have no idea of functions supplied by *.so,
Could any member fix this issue?

**Comment by hongyangqin** [comment]
Python 3.6 to Python 3.9 and Linux are required.
