### ISSUE TITLE
ABS prasing tools have no heroes picture  and models

### ISSUE THREAD

**Issue by Clearqq** [tencent-ailab/hok_env#43]
ABS prasing tools have no heroes picture  and models
![微信截图_20231112145100](https://github.com/tencent-ailab/hok_env/assets/127932466/ee8db4eb-d8fb-4bf3-918e-a2f2d03f6934)

**Comment by hongyangqin** [comment]
> Current supported heroes in hok_env:
> lubanqihao
> miyue
> libai
> makeboluo (Marco Polo)
> direnjie
> guanyu
> diaochan
> luna
> hanxin
> huamulan
> buzhihuowu (Mai Shiranui)
> jvyoujing (Ukyou Tachibana)
> houyi
> zhongkui
> ganjiangmoye
> kai
> gongsunli
> peiqinhu
> shangguanwaner
