### ISSUE TITLE
Read Conf File Error:.\sgame_simulator.common.conf

### ISSUE THREAD

**Issue by M1nOwO** [tencent-ailab/hok_env#45]
Command .\sgame_simulator_remote_zmq.exe .\sgame_simulator.common.conf doesn't work. Error Info is:
Read Conf File Error:.\sgame_simulator.common.conf
Error, Parse Simulator Conf -2
I put the sgame_simulator.common.conf config with the correct content under path \gamecore\bin, but it doesn't work

**Comment by hongyangqin** [comment]
More details please.

**Comment by heartInsert** [comment]
readme里面要.\sgame_simulator_remote_zmq.exe .\sgame_simulator.common.conf ，但是其实sgame_simulator.common.conf 这个文件已经不存在了，所以这个命令还需要执行吗

**Comment by heartInsert** [comment]
> readme里面要.\sgame_simulator_remote_zmq.exe .\sgame_simulator.common.conf ，但是其实sgame_simulator.common.conf 这个文件已经不存在了，所以这个命令还需要执行吗

懂了，其实sgame_simulator.common.conf的内容在下面

**Comment by Feakers-worlds** [comment]
@heartInsert 请问，所以这个文件是要自己写吗？

**Comment by 1329844541** [comment]
所以这个问题要解决吗?我也遇到问题：
Read Conf File Error:.\sgame_simulator.common.conf
Error, Parse Simulator Conf -2

**Comment by 1329844541** [comment]
被蠢哭，自己在同级目录下新建一个sgame_simulator.common.conf，文件内容放下如下（教程给了真的瞎，看不见）：
{
    "abs_file": "../scene/1V1.abs",
    "core_assets": "../core_assets",
    "game_id": "kaiwu-base-35401-35400-6842-1669963820108111766-217",
    "hero_conf": [
        {
            "hero_id": 199
        },
        {
            "hero_id": 199
        }
    ]
}
![屏幕截图 2024-08-05 162703](https://github.com/user-attachments/assets/321d0fb8-3877-4759-839c-bbb8c019ea12)
然后发现bin下多了很多文件：
![887c9ab6388c809ba4d3b700c62e39c](https://github.com/user-attachments/assets/21d9ee90-d8cb-45be-a071-0fa1abe76c4e)

**Comment by env111** [comment]
> 被蠢哭，自己在同级目录下新建一个sgame_simulator.common.conf，文件内容放下如下（教程给了真的瞎，看不见）： { "abs_file": "../scene/1V1.abs", "core_assets": "../core_assets", "game_id": "kaiwu-base-35401-35400-6842-1669963820108111766-217", "hero_conf": [ { "hero_id": 199 }, { "hero_id": 199 } ] } ![屏幕截图 2024-08-05 162703](https://private-user-images.githubusercontent.com/27014937/355030052-321d0fb8-3877-4759-839c-bbb8c019ea12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyODI4MzAsIm5iZiI6MTcyMzI4MjUzMCwicGF0aCI6Ii8yNzAxNDkzNy8zNTUwMzAwNTItMzIxZDBmYjgtMzg3Ny00NzU5LTgzOWMtYmJiOGMwMTllYTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA5MzUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNWZjMjIyZThiYWVmZDE4MTI0MGM1ZDM2ZGQ3YTcwODgzMzdlNDk1NDY0ZDQ1M2M5Yzg1YTFkOWU5ZWM0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IxtQTs4KwlxDEUCgW3TZn6Xi9OZyItEvalpQJnwakCs) 然后发现bin下多了很多文件： ![887c9ab6388c809ba4d3b700c62e39c](https://private-user-images.githubusercontent.com/27014937/355030828-21d9ee90-d8cb-45be-a071-0fa1abe76c4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyODI4MzAsIm5iZiI6MTcyMzI4MjUzMCwicGF0aCI6Ii8yNzAxNDkzNy8zNTUwMzA4MjgtMjFkOWVlOTAtZDhjYi00NWJlLWEwNzEtMGZhMWFiZTc2YzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDA5MzUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZWZkMGRhMzQ4ODI1NTg2YThkNTNhYmM2ZWNmNWQ0OTIyNWE2MTIwNzNiMTQ3OGIwOWFmM2Y4NjRlYWYwOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JZD4YVroWw46r_k1ZmCUZP2ULQ3aV9UWrw1O9n9M4Ks)

谢谢，请问教程链接能发一下吗？ 我看官网的教程好像比较老？有些文件都变了？

**Comment by TimerChen** [comment]
> 谢谢，请问教程链接能发一下吗？ 我看官网的教程好像比较老？有些文件都变了？

中文教程可以参考：https://zhuanlan.zhihu.com/p/704549313
