### ISSUE TITLE
"/rl_framework/gamecore": not found

### ISSUE THREAD

**Issue by haopan27** [tencent-ailab/hok_env#46]
While following the guide [run_windows_gamecore_on_linux](https://github.com/tencent-ailab/hok_env/blob/master/docs/run_windows_gamecore_on_linux.md), and executing the following:
`docker build -f ./dockerfile/dockerfile.gamecore -t ${target_image} --build-arg=BASE_IMAGE=${base_image} .`

I encountered the following ERROR:
`failed to solve: failed to compute cache key: failed to calculate checksum of ref ...:"/rl_framework/gamecore": not found`

The folder "/rl_framework/gamecore" does not exist, and I am not sure what content should reside therein. I guess one has to "Execute gamecore using Wine" first (by following the commands below)?
```
export GAMECORE_PATH=${GAMECORE_PATH:-"/rl_framework/gamecore/"}
export WINEPATH="${GAMECORE_PATH}/lib/;${GAMECORE_PATH}/bin/"

wine ${GAMECORE_PATH}/bin/sgame_simulator_remote_zmq.exe simulator.conf
```

But then, I encountered yet another error, 
`00e8:fixme:ntdll:create_logical_proc_info Improve CPU info reporting: system supports 96 logical cores, but only 64 supported!
wine: failed to open "/rl_framework/gamecore//bin/sgame_simulator_remote_zmq.exe": c0000135`

Highly appreciate it if anyone could shed some light here.

**Comment by hongyangqin** [comment]
Try to fix the `dockerfile.gamecore`:

https://github.com/tencent-ailab/hok_env/blob/master/dockerfile/dockerfile.gamecore#L13

```diff
- RUN mkdir -p =/rl_framework && \
+ RUN mkdir -p /rl_framework && \
    unzip ./hok_env_gamecore.zip -d /rl_framework
```

**Comment by haopan27** [comment]
Thanks for the tip, that did fix the first issue I mentioned.

You may consider this issue closed and I will open up a new issue continuing to resolve the other one I mentioned.

**Comment by haopan27** [comment]
Thanks for the tip, that did fix the first issue I mentioned.

You may consider this issue closed and I will open up a new issue continuing to resolve the other one I mentioned.
