### ISSUE TITLE
`apt install --install-recommends -y winehq-stable` did not complete successfully

### ISSUE THREAD

**Issue by haopan27** [tencent-ailab/hok_env#48]
I am creating this issue for better visibility, as I already described what it was about in my comment [here](https://github.com/tencent-ailab/hok_env/issues/47#issuecomment-1972627721)

I was hoping for a workaround to install winehq on a Centos7 system. Not sure if this is at all possible / anyone has attempted.
Any help is much appreciated on this front.

**Comment by hongyangqin** [comment]
It is ok to use CentOS 7 as the host system and use Ubuntu as the base image of the container. 
The two do not conflict. Just install Docker to your host system and then build the image without changing the base image in dockerfile.

Please refer to [What is a Container?](https://www.docker.com/resources/what-container/) for more details.

**Comment by haopan27** [comment]
I have finally sorted out this issue: the images were created without issues.

To wrap up, one has to perform a few changes in order for this to work:

1. Drop the "=" sign on line 13 in [dockerfile.gamecore](https://github.com/tencent-ailab/hok_env/blob/26d455f6136ea8c6e5b73cf9299f7966ca2dccf5/dockerfile/dockerfile.gamecore#L13)
2. Execute the following commands, instead of those suggested in [run_windows_gamecore_on_linux](https://github.com/tencent-ailab/hok_env/blob/master/docs/run_windows_gamecore_on_linux.md),  to properly perform a multi-stage build

```
base_image=tencentailab/hok_env:cpu_v2.0.1
target_image=final_gamecore
internal_image=gamecore

docker build -f ./dockerfile/dockerfile.gamecore --target gamecore -t ${internal_image} --build-arg BASE_IMAGE=${base_image} .
docker build -f ./dockerfile/dockerfile.gamecore -t ${target_image} --build-arg BASE_IMAGE=${base_image} .
```

What also helped me immensely, was the [dockerfile reference](https://docs.docker.com/reference/dockerfile/), so that I could understand the content inside [dockerfile.gamecore](https://github.com/tencent-ailab/hok_env/blob/master/dockerfile/dockerfile.gamecore).

**Comment by haopan27** [comment]
I have finally sorted out this issue: the images were created without issues.

To wrap up, one has to perform a few changes in order for this to work:

1. Drop the "=" sign on line 13 in [dockerfile.gamecore](https://github.com/tencent-ailab/hok_env/blob/26d455f6136ea8c6e5b73cf9299f7966ca2dccf5/dockerfile/dockerfile.gamecore#L13)
2. Execute the following commands, instead of those suggested in [run_windows_gamecore_on_linux](https://github.com/tencent-ailab/hok_env/blob/master/docs/run_windows_gamecore_on_linux.md),  to properly perform a multi-stage build.
3. Finally make sure that the docker image name is `final_gamecore`, as shown below:
`docker run --network host -e SIMULATOR_USE_WINE=1 -it final_gamecore bash`

```
base_image=tencentailab/hok_env:cpu_v2.0.1
target_image=final_gamecore
internal_image=gamecore

docker build -f ./dockerfile/dockerfile.gamecore --target gamecore -t ${internal_image} --build-arg BASE_IMAGE=${base_image} .
docker build -f ./dockerfile/dockerfile.gamecore -t ${target_image} --build-arg BASE_IMAGE=${base_image} .
```

What also helped me immensely, was the [dockerfile reference](https://docs.docker.com/reference/dockerfile/), so that I could understand the content inside [dockerfile.gamecore](https://github.com/tencent-ailab/hok_env/blob/master/dockerfile/dockerfile.gamecore).
