### ISSUE TITLE
Fail to launch gamecore due to display-related error

### ISSUE THREAD

**Issue by chang-github-00** [tencent-ailab/hok_env#50]
Hi,

I've been trying to launch gamecore on a cluster (linux system) with 
```
export GAMECORE_PATH=${GAMECORE_PATH:-"/rl_framework/gamecore/"}
export WINEPATH="${GAMECORE_PATH}/lib/;${GAMECORE_PATH}/bin/"

wine ${GAMECORE_PATH}/bin/sgame_simulator_remote_zmq.exe simulator.conf
```
and I've got these errors: 
```
001c:err:wineusb:DriverEntry Failed to initialize Unix library, status 0xc0000135.
001c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000135
0016:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\nsiproxy": c0000135
0016:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\NDIS": 00000001
0035:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0035:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
wine: Unhandled page fault on read access to 00000000011582CC at address 0000000180FF5365 (thread 0035), starting debugger...
Can't attach process 0034: error 5
003a:err:winediag:nodrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
```

Is a display required for launching gamecore?  and can it be launched on a training-based cluster with GPUs like Amazon cloud services.

**Comment by chang-github-00** [comment]
I've solved by running docker.

**Comment by chang-github-00** [comment]
Despite I followed the docker installation guide. I still have this error in the test stage when running
`python -c "from hok.hok3v3.unit_test.test_env import run_test; run_test()"`
and error in log file `cat /rl_framework/gamecore/simulator_output/*.log` 

`0098:fixme:ntdll:create_logical_proc_info Improve CPU info reporting: system supports 128 logical cores, but only 64 supported!
...
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 79
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 80
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 81
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 82
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 83
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 84
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 85
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 86
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 87
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 88
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 89
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 90
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 91
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 92
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 93
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 94
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 95
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 96
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 97
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 98
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 99
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 100
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 101
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 102
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 103
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 104
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 105
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 106
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 107
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 108
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 109
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 110
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 111
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 112
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 113
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 114
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 115
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 116
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 117
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 118
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 119
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 120
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 121
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 122
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 123
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 124
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 125
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 126
0108:fixme:ntdll:create_logical_proc_info skipping logical processor 127
0108:fixme:ntdll:NtSetInformationToken unimplemented class 4
0110:fixme:ver:GetCurrentPackageId (00000000013ECCD0 0000000000000000): stub
0108:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0108:fixme:ntdll:NtQuerySystemInformation SystemCodeIntegrityInformation, size 8, info 0x211658, stub!
0108:fixme:ntdll:NtQuerySystemInformation SystemCodeIntegrityInformation, size 8, info 0x211670, stub!
0108:err:winediag:ntlm_check_version ntlm_auth was not found. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0108:err:ntlm:ntlm_LsaApInitializePackage no NTLM support, expect problems
0108:fixme:security:GetWindowsAccountDomainSid (00000000FFFFC2B0 00000000007C2F38 00000000FFFFC2AC): semi-stub
0108:fixme:netapi32:DsEnumerateDomainTrustsW ((null), 0x0023, 00000000FFFFC368, 00000000FFFFC354): stub
0120:fixme:wldap32:ldap_set_optionW Unsupported option: 0x95
0120:fixme:wldap32:ldap_set_optionW Unsupported option: 0x96
0108:fixme:netapi32:NetUserGetInfo Only implemented for local computer, but remote serverL"\\\\@" was requested.
Cygwin WARNING:
  Couldn't compute FAST_CWD pointer.  This typically occurs if you're using
  an older Cygwin version on a newer Windows.  Please update to the latest
  available Cygwin version from https://cygwin.com/.  If the problem persists,
  please see https://cygwin.com/problems.html

0108:fixme:netapi32:NetLocalGroupGetInfo ((null) L"Administrators" 1 00000000FFFFC3E0) semi-stub!
0108:fixme:netapi32:NetLocalGroupGetInfo ((null) L"Users" 1 00000000FFFFC3E0) semi-stub!
0108:fixme:winsock:WSAIoctl SIO_UDP_CONNRESET stub
SGame Simulator Repeated Begin
0124:fixme:ver:GetCurrentPackageId (000000000298CCD0 0000000000000000): stub
init_ret:0
start_ret:0
[Hero Info] [HeroID:139] [RuntimeID:8] client_id:
[Hero Info] [HeroID:139] [RuntimeID:9] client_id:
Begin Request AIServer
boost_ret OverNormally
close_ret:0
uninit_ret:0
SGame Simulator End [FrameNum:8357][TimeUsed:7079ms]`

**Comment by hongyangqin** [comment]
`SGame Simulator End` shows that the gamecore process ended successfully. Can you find the abs file generated (`/rl_framework/gamecore/simulator_output`) and replay it using the `ABSTool.exe`?
