### ISSUE TITLE
error="listen tcp :23432: bind: address already in use"

### ISSUE THREAD

**Issue by haopan27** [tencent-ailab/hok_env#53]
When I checked the `/aiarena/logs/gamecore-server.log` file, I saw the following:

```
level=info msg="start server" Address=":23432" ApiSvcBaseURL= DisableV2api=false Env=dev GamecoreMgr="map[CallBack:[map[] map[Failed:0 Succeed:0 Total:0] map[] map[SaveRate:0.5 SceneManager:map[ABSDir:/r>

level=fatal msg="start server failed" error="listen tcp :23432: bind: address already in use"
```

I am not sure if this `address already in use` message is normal. I was able to send the test client 
`python3 /rl_framework/remote-gc-server/test_client.py`,
and even obtain the replay files after running 1v1 games:

```
cd /hok_env/hok/hok1v1/unit_test
python3 ./test_env.py
```

Please advise how one should fix the issue if the error message is not to be expected.

**Comment by hongyangqin** [comment]
The gamecore server is started. No need to run it again. It's ok to ignore this message.
