### ISSUE TITLE
Gamecore failed to start on Windows 10 (inner version: 19044.2006)

### ISSUE THREAD

**Issue by yuanjianrui** [tencent-ailab/hok_env#6]
I have copyed licence.dat to hok_env_gamecore/gamecore/core_assets, thanks for your kindly help on that. Then I add the folder " hok_env_gamecore/gamecore/core_assets" to the system environment variable "PATH" as some dll files needed by sgame_simulator_remote_zmq.exe are stored in the folder core_assets.

There is no directory named _ai_simulator_remote_ in hok_env_gamecore folder.  I do nothing here. 

Then I start the gamecore by first "cd hok_env_gamecore/gamecore", and then ".\sgame_simulator_remote_zmq.exe "2022" .\sgame_simulator.conf" 

I get the following output on my screen:

```
PlayerNum:2
AbsPath:./1V1.abs
PlayerInfo [CampID:0][HeroID:146][Skill:80121][AutoAi:0][AiServer:127.0.0.1:35300:1000] [Symbol 0 0 0] [Request:-1]
PlayerInfo [CampID:1][HeroID:146][Skill:80121][AutoAi:0][AiServer:127.0.0.1:35301:1000] [Symbol 0 0 0] [Request:-1]
SGame Simulator Begin
init_ret:0
seed: 3417
Symbols:
inHeroId: 146
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
inHeroId: 146
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
start_ret:0
Hero[0] inHeroId:146; outPlayerId:148
Hero[1] inHeroId:146; outPlayerId:149
frame no:0
begin_ret:0
[Hero Info] [HeroID:146] [RuntimeID:8] client_id:0.0.0.0_1859_0_20221003174931_148
[Hero Info] [HeroID:146] [RuntimeID:9] client_id:0.0.0.0_1859_0_20221003174931_149
zmq socket init success
addr: tcp://127.0.0.1:35300
zmq socket connect success
recv failed2: -1
```

The zmq socket for the second hero failed to start. Then I changed the port 35301 written in .\sgame_simulator.conf  to some other ports (in order to avoiding port confliction),  the gamecore still print the same error messages. 

Do you know what is wrong here, and how can we fix the above issue?

**Comment by LostThinker** [comment]
I had the same problem .I run ".\sgame_simulator_remote_zmq.exe "2022" .\sgame_simulator.conf" in the powershell locally and get "recv failed2: -1". How to solve this problem

**Comment by liyuxuan-academic** [comment]
> I am having the same problem here and I would suggest an updated README.md, which would be a great help. 
Further to hongyangqin's reply, I wonder where do I start the mentioned `simulator` ?

**Comment by spirlness** [comment]
I had the same problem .I run ".\sgame_simulator_remote_zmq.exe "2022" .\sgame_simulator.conf" in the powershell locally and get "recv failed2: -1",and I have copyed licence.dat to hok_env_gamecore/gamecore/core_assets,  Then I add the folder " hok_env_gamecore/gamecore/core_assets" to the system environment variable "PATH" .the begin_ret:0 shows that the license.dat worked.I would like to ask for your help in solving this problem，You can also suggest some suggestions that might work。Thank you for your help on hok-env.
My input command line is shown below

PlayerNum:2
AbsPath:./1V1.abs
PlayerInfo [CampID:0][HeroID:146][Skill:80121][AutoAi:0][AiServer:127.0.0.1:35300:1000] [Symbol 0 0 0] [Request:-1]
PlayerInfo [CampID:1][HeroID:146][Skill:80121][AutoAi:0][AiServer:127.0.0.1:35301:1000] [Symbol 0 0 0] [Request:-1]
SGame Simulator Begin
init_ret:0
seed: 3417
Symbols:
inHeroId: 146
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
inHeroId: 146
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
start_ret:0
Hero[0] inHeroId:146; outPlayerId:148
Hero[1] inHeroId:146; outPlayerId:149
frame no:0
begin_ret:0
[Hero Info] [HeroID:146] [RuntimeID:8] client_id:0.0.0.0_1859_0_20221003174931_148
[Hero Info] [HeroID:146] [RuntimeID:9] client_id:0.0.0.0_1859_0_20221003174931_149
zmq socket init success
addr: tcp://127.0.0.1:35300
zmq socket connect success
recv failed2: -1
（My system version：WIN11 Pro version 21H2）

**Comment by TownYan** [comment]
> > I am having the same problem here and I would suggest an updated README.md, which would be a great help.
> > Further to @hongyangqin 's reply, I wonder where do I start the mentioned `simulator` ?

I have the same problem..... Sorry for not knowing what's the mentioned `simulator`. @hongyangqin

**Comment by hongyangqin** [comment]
We commit a fix this week, please retry.

**Comment by liyuxuan-academic** [comment]
> We commit a fix this week, please retry.

The recent updates seemingly only involves updates in `README.md`. Retrying according to new instructions does not help. It still yields outputs including `recv failed2: -1` as this issue's original poster reports. 
Recalling previous replies in this thread, @hongyangqin mentioned something called `simulator`. My appreciation if maintainers could elaborate more over this matter. Like, Is `simulator` openly available? It is no where to be found in this repo at the moment.

**Comment by yuliu77** [comment]
> We commit a fix this week, please retry.

yeah same issue here. Tried with the latest gamecore downloaded from https://aiarena.tencent.com/aiarena/en/open-gamecore. But still getting **recv failed2: -1**

**Comment by yang05941601** [comment]
Mark+1. I find that when I choose the "sgame_simulator_common.conf", it can work successfully.

**Comment by hongyangqin** [comment]
@liyuxuan-academic @TownYan https://aiarena.tencent.com/aiarena/en/open-gamecore

**Comment by L3Y1Q2** [comment]
@hongyangqin 

![软件无法使用](https://user-images.githubusercontent.com/23252875/205573521-ebd45cab-c87a-4f34-9752-3072e9158798.JPG)
1. Upon running this command, my system (Win10 21H2 19044.2251) shows the problem.
2. Please update the README.
![README](https://user-images.githubusercontent.com/23252875/205577094-1e0d52cc-449e-4a60-ac48-5e87a3f0b240.JPG)

**Comment by Amberjay18** [comment]
> We commit a fix this week, please retry.
Sorry, I still met this issue:
**_Read Conf file Error: .\sgame_simulator.common.conf
Error,Parse Simulator Conf -2_**
BTW, please @hongyangqin  update the README 
(there no folder named **ai_simulator_remote**, maybe named _gamecore_ ???) 
Thank you so much.

**Comment by hongyangqin** [comment]
@Amberjay18 Yes, It is the `gamecore`. We provide the `gamecore-server` after this commit.

**Comment by Amberjay18** [comment]
> @Amberjay18 Yes, It is the `gamecore`. We provide the `gamecore-server` after this commit.

hi, @hongyangqin 
I have resolved this problem!!!thank you so much.
BTW, how I am resolved it as below.

- First, I changed the **sgame_simulator_remote_zmq.conf.example file content** according to docuement, and **renamed the file to sgame_simulator.common.conf**.
- Second,I added the path of **gamecore bin,lib folders to the system environment variables.**
- Third,I **started the gamecore-server.exe in the CMD before go ahead to gamecore bin** folder.

Maybe this solution not suit for everyone, but you can try.
