### ISSUE TITLE
observation 的维度是705，请问每个维度代表什么意思，有说明吗？

### ISSUE THREAD

**Issue by Akon-Fiber** [tencent-ailab/hok_env#66]
observation 的维度是705，请问每个维度代表什么意思，有说明吗？

**Comment by 1329844541** [comment]
你是怎么安装成功的。我1v1的demo都没跑通，感觉也没有人维护这个项目了

**Comment by Akon-Fiber** [comment]
> 你是怎么安装成功的。我1v1的demo都没跑通，感觉也没有人维护这个项目了

gamecore安装在windows下，sdk我用的里面提供的镜像。

**Comment by hongyangqin** [comment]
目前暂无, 后续会更新提供
重复: #25

**Comment by Akon-Fiber** [comment]
> 目前暂无, 后续会更新提供 重复: #25
期待你们的更新，我这边主要是想用LLM进行尝试，所以希望可以提取observation部分信息，并转化为自然语言

**Comment by JackyXiangcheng** [comment]
> > 目前暂无, 后续会更新提供 重复: [#25](https://github.com/tencent-ailab/hok_env/issues/25)
> > 期待你们的更新，我这边主要是想用LLM进行尝试，所以希望可以提取observation部分信息，并转化为自然语言

@Akon-Fiber 您好，现在observation的维度是725，具体内容如下：

<img width="823" height="773" alt="Image" src="https://github.com/user-attachments/assets/b046b7bf-c2b4-41b1-95cc-ccf02dfc3c1f" />
