### ISSUE TITLE
My PC runs badly when I turn WSL on

### ISSUE THREAD

**Issue by Levine02** [tencent-ailab/hok_env#7]
Is it possible to put the training side on a separate Linux server instead of running on a Windows container via WSL. If so, what should I do?

**Comment by hongyangqin** [comment]
Yes, you can run the hok_env on a linux server instead of WSL and manage the gamecore via a gamecore server. The gamecore is only support windows now.

**Comment by Levine02** [comment]
Appreciate it.I wonder how can I connect my gamecore which is on windows with my remote Linux server?Which file should I edit?It will literally helps me a lot if you could give me some tips.

**Comment by hongyangqin** [comment]
> Appreciate it.I wonder how can I connect my gamecore which is on windows with my remote Linux server?Which file should I edit?It will literally helps me a lot if you could give me some tips.

A gamecore server that processes game requests from Linux is coming soon.

**Comment by hongyangqin** [comment]
`gamecore-server` is released, please download the latest gamecore package (2022-12-02) and update to the latest code (v1.1.0)

![image](https://user-images.githubusercontent.com/17291060/205415698-235b1385-bd4d-4c24-8a62-46b1d123ef86.png)
